---
- name: check exists docker
  stat: path='/usr/bin/docker'
  register: is_docker
  tags: [ 'docker' ]

- name: install dependency packages
  apt:
    name: [ 'ca-certificates', 'curl', 'gnupg', 'lsb-release' ]
    state: present
    update_cache: yes
  when: not is_docker.stat.exists
  tags: [ 'docker' ]

- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  when: not is_docker.stat.exists
  tags: [ 'docker' ]

- name: add docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
  when: not is_docker.stat.exists
  tags: [ 'docker' ]

- name: install docker packages
  apt:
    name: [ 'docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin' ]
    state: present
  when: not is_docker.stat.exists
  tags: [ 'docker' ]

- name: ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: [ 'docker' ]

- name: add user to docker group
  user: 
    name: '{{ docker_user }}'
    groups: docker
    append: yes
  when: not is_docker.stat.exists
  tags: [ 'docker' ]
